### ISSUE TITLE
Not Logging for Android

### ISSUE THREAD

**Issue by gujjar1988** [kuntal811/flutter_papertrail_alt#1]
It's not working for Android in flutter project.
And you please update build.gradle settings with     ext.kotlin_version = '1.7.10'

I got logs for iOS but android is not working there.

**Comment by kuntal811** [comment]
> It's not working for Android in flutter project. And you please update build.gradle settings with ext.kotlin_version = '1.7.10'
> 
> I got logs for iOS but android is not working there.
@gujjar1988 have you tried to run the example app?
